export default [
  {
    Character: '的',
    Pinyin: 'de',
    Definition: 'possessive, adjectival suffix',
    Frequency: 1,
  },
  {
    Character: '一',
    Pinyin: 'yī',
    Definition: 'one; a, an; alone',
    Frequency: 2,
  },
  {
    Character: '是',
    Pinyin: 'shì',
    Definition: 'indeed, yes, right; to be; demonstrative pronoun, this, that',
    Frequency: 3,
  },
  {
    Character: '不',
    Pinyin: 'bù',
    Definition: 'no, not; un-; negative prefix',
    Frequency: 4,
  },
  {
    Character: '了',
    Pinyin: 'le',
    Definition: 'to finish; particle of completed action',
    Frequency: 5,
  },
  {
    Character: '在',
    Pinyin: 'zài',
    Definition: 'be at, in, on; consist in, rest',
    Frequency: 6,
  },
  {
    Character: '人',
    Pinyin: 'rén',
    Definition: 'man; people; mankind; someone else',
    Frequency: 7,
  },
  {
    Character: '有',
    Pinyin: 'yǒu',
    Definition: 'have, own, possess; exist',
    Frequency: 8,
  },
  {
    Character: '我',
    Pinyin: 'wǒ',
    Definition: 'our, us, i, me, my, we',
    Frequency: 9,
  },
  {
    Character: '他',
    Pinyin: 'tā',
    Definition: 'other, another; he, she, it',
    Frequency: 10,
  },
  {
    Character: '这',
    Pinyin: 'zhè',
    Definition: 'this, the, here',
    Frequency: 11,
  },
  {
    Character: '个',
    Pinyin: 'gè',
    Definition: 'numerary adjunct, piece; single',
    Frequency: 12,
  },
  {
    Character: '们',
    Pinyin: 'men',
    Definition: 'adjunct pronoun indicate plural',
    Frequency: 13,
  },
  {
    Character: '中',
    Pinyin: 'zhōng',
    Definition:
      'central; center, middle; in the midst of; hit (target); attain',
    Frequency: 14,
  },
  {
    Character: '来',
    Pinyin: 'lái',
    Definition: 'come, coming; return, returning',
    Frequency: 15,
  },
  {
    Character: '上',
    Pinyin: 'shàng',
    Definition: 'top; superior, highest; go up, send up',
    Frequency: 16,
  },
  {
    Character: '大',
    Pinyin: 'dà',
    Definition: 'big, great, vast, large, high',
    Frequency: 17,
  },
  {
    Character: '为',
    Pinyin: 'wèi',
    Definition: 'do, handle, govern, act; be',
    Frequency: 18,
  },
  {
    Character: '和',
    Pinyin: 'hé',
    Definition: 'harmony, peace; peaceful, calm',
    Frequency: 19,
  },
  {
    Character: '国',
    Pinyin: 'guó',
    Definition: 'nation, country, nation-state',
    Frequency: 20,
  },
  {
    Character: '地',
    Pinyin: 'de',
    Definition: 'earth; soil, ground; region',
    Frequency: 21,
  },
  {
    Character: '到',
    Pinyin: 'dào',
    Definition: 'go to, arrive, been to',
    Frequency: 22,
  },
  {
    Character: '以',
    Pinyin: 'yǐ',
    Definition: 'by means of; thereby, therefore; consider as; in order to',
    Frequency: 23,
  },
  {
    Character: '说',
    Pinyin: 'shuō',
    Definition: 'speak, say, talk; scold, upbraid',
    Frequency: 24,
  },
  {
    Character: '时',
    Pinyin: 'shí',
    Definition: 'time, season; era, age, period',
    Frequency: 25,
  },
  {
    Character: '要',
    Pinyin: 'yào',
    Definition: 'necessary, essential; necessity',
    Frequency: 26,
  },
  {
    Character: '就',
    Pinyin: 'jiù',
    Definition: 'just, simply; to come, go to; to approach, near',
    Frequency: 27,
  },
  {
    Character: '出',
    Pinyin: 'chū',
    Definition: 'go out, send out; stand; produce',
    Frequency: 28,
  },
  {
    Character: '会',
    Pinyin: 'huì',
    Definition: 'assemble, meet together; meeting',
    Frequency: 29,
  },
  {
    Character: '可',
    Pinyin: 'kě',
    Definition: 'may, can, -able; possibly',
    Frequency: 30,
  },
  {
    Character: '也',
    Pinyin: 'yě',
    Definition:
      'also; classical final particle of strong affirmation or identity',
    Frequency: 31,
  },
  {
    Character: '你',
    Pinyin: 'nǐ',
    Definition: 'you, second person pronoun',
    Frequency: 32,
  },
  {
    Character: '对',
    Pinyin: 'duì',
    Definition: 'correct, right; facing, opposed',
    Frequency: 33,
  },
  {
    Character: '生',
    Pinyin: 'shēng',
    Definition: 'life, living, lifetime; birth',
    Frequency: 34,
  },
  {
    Character: '能',
    Pinyin: 'néng',
    Definition: 'to be able; can, permitted to; ability',
    Frequency: 35,
  },
  {
    Character: '而',
    Pinyin: 'ér',
    Definition: 'and; and then; and yet; but',
    Frequency: 36,
  },
  {
    Character: '子',
    Pinyin: 'zi',
    Definition: 'offspring, child; fruit, seed of; 1st terrestrial branch',
    Frequency: 37,
  },
  {
    Character: '那',
    Pinyin: 'nà',
    Definition: 'that, that one, those',
    Frequency: 38,
  },
  {
    Character: '得',
    Pinyin: 'dé',
    Definition: 'obtain, get, gain, acquire',
    Frequency: 39,
  },
  {
    Character: '于',
    Pinyin: 'yú',
    Definition: 'in, on, at; go to; surname',
    Frequency: 40,
  },
  {
    Character: '着',
    Pinyin: 'zhe',
    Definition: 'make move, take action',
    Frequency: 41,
  },
  {
    Character: '下',
    Pinyin: 'xià',
    Definition: 'under, underneath, below; down; inferior; bring down',
    Frequency: 42,
  },
  {
    Character: '自',
    Pinyin: 'zì',
    Definition: 'self, private, personal; from',
    Frequency: 43,
  },
  {
    Character: '之',
    Pinyin: 'zhī',
    Definition:
      'marks preceding phrase as modifier of following phrase; it, him her, them; go to',
    Frequency: 44,
  },
  { Character: '年', Pinyin: 'nián', Definition: '', Frequency: 45 },
  {
    Character: '过',
    Pinyin: 'guò',
    Definition: 'pass, pass through, go across',
    Frequency: 46,
  },
  {
    Character: '发',
    Pinyin: 'fā',
    Definition: 'issue, dispatch, send out; hair',
    Frequency: 47,
  },
  {
    Character: '后',
    Pinyin: 'hòu',
    Definition: 'queen, empress, sovereign; (simp. for 後) behind, rear, after',
    Frequency: 48,
  },
  {
    Character: '作',
    Pinyin: 'zuò',
    Definition: 'make; work; compose, write; act, perform',
    Frequency: 49,
  },
  {
    Character: '里',
    Pinyin: 'lǐ',
    Definition: 'unit of distance; village; lane',
    Frequency: 50,
  },
  {
    Character: '用',
    Pinyin: 'yòng',
    Definition: 'use, employ, apply, operate; use',
    Frequency: 51,
  },
  {
    Character: '道',
    Pinyin: 'dào',
    Definition: 'path, road, street; method, way',
    Frequency: 52,
  },
  {
    Character: '行',
    Pinyin: 'xíng',
    Definition: 'go; walk; move, travel; circulate',
    Frequency: 53,
  },
  {
    Character: '所',
    Pinyin: 'suǒ',
    Definition: 'place, location; numerary adjunct',
    Frequency: 54,
  },
  {
    Character: '然',
    Pinyin: 'rán',
    Definition: 'yes, certainly; pledge, promise',
    Frequency: 55,
  },
  {
    Character: '家',
    Pinyin: 'jiā',
    Definition: 'house, home, residence; family',
    Frequency: 56,
  },
  {
    Character: '种',
    Pinyin: 'zhǒng',
    Definition: 'seed; race, breed; to plant',
    Frequency: 57,
  },
  {
    Character: '事',
    Pinyin: 'shì',
    Definition: 'affair, matter, business; to serve; accident, incident',
    Frequency: 58,
  },
  {
    Character: '成',
    Pinyin: 'chéng',
    Definition: 'completed, finished, fixed',
    Frequency: 59,
  },
  {
    Character: '方',
    Pinyin: 'fāng',
    Definition: 'a square, rectangle; a region; local',
    Frequency: 60,
  },
  {
    Character: '多',
    Pinyin: 'duō',
    Definition: 'much, many; more than, over',
    Frequency: 61,
  },
  {
    Character: '经',
    Pinyin: 'jīng',
    Definition: 'classic works; pass through',
    Frequency: 62,
  },
  {
    Character: '么',
    Pinyin: 'me',
    Definition: 'interrogative particle; repetition of a tune small; tender',
    Frequency: 63,
  },
  {
    Character: '去',
    Pinyin: 'qù',
    Definition: 'go away, leave, depart',
    Frequency: 64,
  },
  {
    Character: '法',
    Pinyin: 'fǎ',
    Definition: 'law, rule, regulation, statute; France, French',
    Frequency: 65,
  },
  {
    Character: '学',
    Pinyin: 'xué',
    Definition: 'learning, knowledge; school',
    Frequency: 66,
  },
  {
    Character: '如',
    Pinyin: 'rú',
    Definition: 'if, supposing; as if; like, as',
    Frequency: 67,
  },
  {
    Character: '都',
    Pinyin: 'dōu',
    Definition: 'metropolis, capital; all, the whole; elegant, refined',
    Frequency: 68,
  },
  {
    Character: '同',
    Pinyin: 'tóng',
    Definition: 'same, similar; together with',
    Frequency: 69,
  },
  {
    Character: '现',
    Pinyin: 'xiàn',
    Definition: 'appear, manifest, become visible',
    Frequency: 70,
  },
  {
    Character: '当',
    Pinyin: 'dāng',
    Definition: 'bear, accept, undertake; just',
    Frequency: 71,
  },
  {
    Character: '没',
    Pinyin: 'méi',
    Definition: 'not, have not, none; drown, sink',
    Frequency: 72,
  },
  {
    Character: '动',
    Pinyin: 'dòng',
    Definition: 'move, happen; movement, action',
    Frequency: 73,
  },
  {
    Character: '面',
    Pinyin: 'miàn',
    Definition: 'face; surface; plane; side, dimension',
    Frequency: 74,
  },
  {
    Character: '起',
    Pinyin: 'qǐ',
    Definition: 'rise, stand up; go up; begin',
    Frequency: 75,
  },
  {
    Character: '看',
    Pinyin: 'kàn',
    Definition: 'look, see; examine, scrutinize',
    Frequency: 76,
  },
  {
    Character: '定',
    Pinyin: 'dìng',
    Definition: 'decide, settle, fix',
    Frequency: 77,
  },
  {
    Character: '天',
    Pinyin: 'tiān',
    Definition: 'sky, heaven; god, celestial',
    Frequency: 78,
  },
  {
    Character: '分',
    Pinyin: 'fēn',
    Definition: 'divide; small unit of time etc.',
    Frequency: 79,
  },
  {
    Character: '还',
    Pinyin: 'hái',
    Definition: 'still, yet, also, besides',
    Frequency: 80,
  },
  {
    Character: '进',
    Pinyin: 'jìn',
    Definition: 'advance, make progress, enter',
    Frequency: 81,
  },
  {
    Character: '好',
    Pinyin: 'hǎo',
    Definition: 'good, excellent, fine; well',
    Frequency: 82,
  },
  {
    Character: '小',
    Pinyin: 'xiǎo',
    Definition: 'small, tiny, insignificant',
    Frequency: 83,
  },
  {
    Character: '部',
    Pinyin: 'bù',
    Definition: 'part, division, section',
    Frequency: 84,
  },
  {
    Character: '其',
    Pinyin: 'qí',
    Definition: 'his, her, its, their; that',
    Frequency: 85,
  },
  {
    Character: '些',
    Pinyin: 'xiē',
    Definition: 'little, few; rather, somewhat',
    Frequency: 86,
  },
  {
    Character: '主',
    Pinyin: 'zhǔ',
    Definition: 'master, chief owner; host; lord',
    Frequency: 87,
  },
  {
    Character: '样',
    Pinyin: 'yàng',
    Definition: 'shape, form, pattern, style',
    Frequency: 88,
  },
  {
    Character: '理',
    Pinyin: 'lǐ',
    Definition: 'reason, logic; manage',
    Frequency: 89,
  },
  {
    Character: '心',
    Pinyin: 'xīn',
    Definition: 'heart; mind, intelligence; soul',
    Frequency: 90,
  },
  { Character: '她', Pinyin: 'tā', Definition: 'she, her', Frequency: 91 },
  {
    Character: '本',
    Pinyin: 'běn',
    Definition: 'root, origin, source; basis',
    Frequency: 92,
  },
  {
    Character: '前',
    Pinyin: 'qián',
    Definition: 'in front, forward; preceding',
    Frequency: 93,
  },
  {
    Character: '开',
    Pinyin: 'kāi',
    Definition: 'open; initiate, begin, start',
    Frequency: 94,
  },
  {
    Character: '但',
    Pinyin: 'dàn',
    Definition: 'only; but, however, yet, still',
    Frequency: 95,
  },
  {
    Character: '因',
    Pinyin: 'yīn',
    Definition: 'cause, reason; by; because (of)',
    Frequency: 96,
  },
  {
    Character: '只',
    Pinyin: 'zhǐ',
    Definition: 'only, just, simply',
    Frequency: 97,
  },
  {
    Character: '从',
    Pinyin: 'cóng',
    Definition: 'from, by, since, whence, through',
    Frequency: 98,
  },
  {
    Character: '想',
    Pinyin: 'xiǎng',
    Definition: 'think, speculate, plan, consider',
    Frequency: 99,
  },
  {
    Character: '实',
    Pinyin: 'shí',
    Definition: 'real, true; honest, sincere',
    Frequency: 100,
  },
  {
    Character: '日',
    Pinyin: 'rì',
    Definition: 'sun; day; daytime',
    Frequency: 101,
  },
  {
    Character: '军',
    Pinyin: 'jūn',
    Definition: 'army, military; soldiers, troops',
    Frequency: 102,
  },
  {
    Character: '者',
    Pinyin: 'zhě',
    Definition: 'that which; he who; those who',
    Frequency: 103,
  },
  {
    Character: '意',
    Pinyin: 'yì',
    Definition: 'thought, idea, opinion; think',
    Frequency: 104,
  },
  {
    Character: '无',
    Pinyin: 'wú',
    Definition: 'negative, no, not; KangXi radical 71',
    Frequency: 105,
  },
  {
    Character: '力',
    Pinyin: 'lì',
    Definition: 'power, capability, influence',
    Frequency: 106,
  },
  { Character: '它', Pinyin: 'tā', Definition: 'it; other', Frequency: 107 },
  {
    Character: '与',
    Pinyin: 'yǔ',
    Definition: 'and; with; to; for; give, grant',
    Frequency: 108,
  },
  {
    Character: '长',
    Pinyin: 'zhǎng',
    Definition: 'long; length; excel in; leader',
    Frequency: 109,
  },
  {
    Character: '把',
    Pinyin: 'bǎ',
    Definition: 'hold, take; guard; regard as',
    Frequency: 110,
  },
  {
    Character: '机',
    Pinyin: 'jī',
    Definition: 'desk; machine; moment',
    Frequency: 111,
  },
  {
    Character: '十',
    Pinyin: 'shí',
    Definition: 'ten, tenth; complete; perfect',
    Frequency: 112,
  },
  {
    Character: '民',
    Pinyin: 'mín',
    Definition: 'people, subjects, citizens',
    Frequency: 113,
  },
  {
    Character: '第',
    Pinyin: 'dì',
    Definition: 'sequence, number; grade, degree',
    Frequency: 114,
  },
  {
    Character: '公',
    Pinyin: 'gōng',
    Definition: 'fair, equitable; public; duke',
    Frequency: 115,
  },
  {
    Character: '此',
    Pinyin: 'cǐ',
    Definition: 'this, these; in this case, then',
    Frequency: 116,
  },
  {
    Character: '已',
    Pinyin: 'yǐ',
    Definition: 'already; finished; stop',
    Frequency: 117,
  },
  {
    Character: '工',
    Pinyin: 'gōng',
    Definition: 'labor, work; worker, laborer',
    Frequency: 118,
  },
  {
    Character: '使',
    Pinyin: 'shǐ',
    Definition: 'cause, send on a mission, order; envoy, messenger, ambassador',
    Frequency: 119,
  },
  {
    Character: '情',
    Pinyin: 'qíng',
    Definition: 'feeling, sentiment, emotion',
    Frequency: 120,
  },
  {
    Character: '明',
    Pinyin: 'míng',
    Definition: 'bright, light, brilliant; clear',
    Frequency: 121,
  },
  {
    Character: '性',
    Pinyin: 'xìng',
    Definition: 'nature, character, sex',
    Frequency: 122,
  },
  {
    Character: '知',
    Pinyin: 'zhī',
    Definition: 'know, perceive, comprehend',
    Frequency: 123,
  },
  {
    Character: '全',
    Pinyin: 'quán',
    Definition: 'maintain, keep whole or intact',
    Frequency: 124,
  },
  { Character: '三', Pinyin: 'sān', Definition: 'three', Frequency: 125 },
  {
    Character: '又',
    Pinyin: 'yòu',
    Definition: 'and, also, again, in addition',
    Frequency: 126,
  },
  {
    Character: '关',
    Pinyin: 'guān',
    Definition: 'frontier pass; close; relation',
    Frequency: 127,
  },
  {
    Character: '点',
    Pinyin: 'diǎn',
    Definition: 'dot, speck, spot; point, degree',
    Frequency: 128,
  },
  {
    Character: '正',
    Pinyin: 'zhèng',
    Definition: 'right, proper, correct',
    Frequency: 129,
  },
  {
    Character: '业',
    Pinyin: 'yè',
    Definition: 'profession, business; GB radical 111',
    Frequency: 130,
  },
  {
    Character: '外',
    Pinyin: 'wài',
    Definition: 'out, outside, external; foreign',
    Frequency: 131,
  },
  {
    Character: '将',
    Pinyin: 'jiāng',
    Definition: 'will, going to, future; general',
    Frequency: 132,
  },
  {
    Character: '两',
    Pinyin: 'liǎng',
    Definition: 'two, both, pair, couple; ounce',
    Frequency: 133,
  },
  {
    Character: '高',
    Pinyin: 'gāo',
    Definition: 'high, tall; lofty, elevated',
    Frequency: 134,
  },
  {
    Character: '间',
    Pinyin: 'jiān',
    Definition: 'midpoint, space; place, locality',
    Frequency: 135,
  },
  {
    Character: '由',
    Pinyin: 'yóu',
    Definition: 'cause, reason; from',
    Frequency: 136,
  },
  {
    Character: '问',
    Pinyin: 'wèn',
    Definition: 'ask about, inquire after',
    Frequency: 137,
  },
  {
    Character: '很',
    Pinyin: 'hěn',
    Definition: 'very, quite, much',
    Frequency: 138,
  },
  {
    Character: '最',
    Pinyin: 'zuì',
    Definition: 'most, extremely, exceedingly',
    Frequency: 139,
  },
  {
    Character: '重',
    Pinyin: 'zhòng',
    Definition: 'heavy, weighty; double',
    Frequency: 140,
  },
  { Character: '并', Pinyin: 'bìng', Definition: '', Frequency: 141 },
  {
    Character: '物',
    Pinyin: 'wù',
    Definition: 'thing, substance, creature',
    Frequency: 142,
  },
  { Character: '手', Pinyin: 'shǒu', Definition: 'hand', Frequency: 143 },
  {
    Character: '应',
    Pinyin: 'yīng',
    Definition: 'should, ought to, must',
    Frequency: 144,
  },
  {
    Character: '战',
    Pinyin: 'zhàn',
    Definition: 'war, fighting, battle',
    Frequency: 145,
  },
  {
    Character: '向',
    Pinyin: 'xiàng',
    Definition: 'toward, direction, trend',
    Frequency: 146,
  },
  {
    Character: '头',
    Pinyin: 'tóu',
    Definition: 'head; top; chief, first; boss',
    Frequency: 147,
  },
  {
    Character: '文',
    Pinyin: 'wén',
    Definition: 'literature, culture, writing',
    Frequency: 148,
  },
  {
    Character: '体',
    Pinyin: 'tǐ',
    Definition: 'body; group, class, body, unit; inferior',
    Frequency: 149,
  },
  {
    Character: '政',
    Pinyin: 'zhèng',
    Definition: 'government, political affairs',
    Frequency: 150,
  },
  {
    Character: '美',
    Pinyin: 'měi',
    Definition: 'beautiful, pretty; pleasing',
    Frequency: 151,
  },
  {
    Character: '相',
    Pinyin: 'xiāng',
    Definition: 'mutual, reciprocal, each other',
    Frequency: 152,
  },
  {
    Character: '见',
    Pinyin: 'jiàn',
    Definition: 'see, observe, behold; perceive',
    Frequency: 153,
  },
  { Character: '被', Pinyin: 'bèi', Definition: '', Frequency: 154 },
  {
    Character: '利',
    Pinyin: 'lì',
    Definition: 'gains, advantage, profit, merit',
    Frequency: 155,
  },
  {
    Character: '什',
    Pinyin: 'shén',
    Definition: 'file of ten soldiers; mixed, miscellaneous',
    Frequency: 156,
  },
  { Character: '二', Pinyin: 'èr', Definition: 'two; twice', Frequency: 157 },
  { Character: '等', Pinyin: 'děng', Definition: '', Frequency: 158 },
  {
    Character: '产',
    Pinyin: 'chǎn',
    Definition: 'give birth, bring forth, produce',
    Frequency: 159,
  },
  {
    Character: '或',
    Pinyin: 'huò',
    Definition: 'or, either, else; perhaps, maybe',
    Frequency: 160,
  },
  {
    Character: '新',
    Pinyin: 'xīn',
    Definition: 'new, recent, fresh, modern',
    Frequency: 161,
  },
  {
    Character: '己',
    Pinyin: 'jǐ',
    Definition: 'self, oneself; personal, private; 6th heavenly stem',
    Frequency: 162,
  },
  {
    Character: '制',
    Pinyin: 'zhì',
    Definition: 'system; establish; overpower',
    Frequency: 163,
  },
  {
    Character: '身',
    Pinyin: 'shēn',
    Definition: 'body; trunk, hull; rad. no. 158',
    Frequency: 164,
  },
  {
    Character: '果',
    Pinyin: 'guǒ',
    Definition: 'fruit; result',
    Frequency: 165,
  },
  {
    Character: '加',
    Pinyin: 'jiā',
    Definition: 'add to, increase, augment',
    Frequency: 166,
  },
  {
    Character: '西',
    Pinyin: 'xī',
    Definition: 'west(ern); westward, occident',
    Frequency: 167,
  },
  {
    Character: '斯',
    Pinyin: 'sī',
    Definition: 'this, thus, such; to lop off; emphatic particle',
    Frequency: 168,
  },
  {
    Character: '月',
    Pinyin: 'yuè',
    Definition: 'moon; month; KangXi radical 74',
    Frequency: 169,
  },
  {
    Character: '话',
    Pinyin: 'huà',
    Definition: 'speech, talk, language; dialect',
    Frequency: 170,
  },
  {
    Character: '合',
    Pinyin: 'hé',
    Definition: 'combine, unite, join; gather',
    Frequency: 171,
  },
  {
    Character: '回',
    Pinyin: 'huí',
    Definition: 'return, turn around; a time',
    Frequency: 172,
  },
  {
    Character: '特',
    Pinyin: 'tè',
    Definition: 'special, unique, distinguished',
    Frequency: 173,
  },
  {
    Character: '代',
    Pinyin: 'dài',
    Definition:
      'replace, replacement (of person or generation); era, generation',
    Frequency: 174,
  },
  { Character: '内', Pinyin: 'nèi', Definition: 'inside', Frequency: 175 },
  {
    Character: '信',
    Pinyin: 'xìn',
    Definition: 'trust, believe; letter',
    Frequency: 176,
  },
  {
    Character: '表',
    Pinyin: 'biǎo',
    Definition: 'show, express, manifest, display',
    Frequency: 177,
  },
  {
    Character: '化',
    Pinyin: 'huà',
    Definition: 'change, convert, reform; -ize',
    Frequency: 178,
  },
  {
    Character: '老',
    Pinyin: 'lǎo',
    Definition: 'old, aged; experienced',
    Frequency: 179,
  },
  {
    Character: '给',
    Pinyin: 'gěi',
    Definition: 'give; by, for',
    Frequency: 180,
  },
  {
    Character: '世',
    Pinyin: 'shì',
    Definition: 'generation; world; era',
    Frequency: 181,
  },
  {
    Character: '位',
    Pinyin: 'wèi',
    Definition: 'throne; position, post; rank, status; seat',
    Frequency: 182,
  },
  {
    Character: '次',
    Pinyin: 'cì',
    Definition: 'order, sequence; next',
    Frequency: 183,
  },
  {
    Character: '度',
    Pinyin: 'dù',
    Definition: 'degree, system; manner; to consider',
    Frequency: 184,
  },
  {
    Character: '门',
    Pinyin: 'mén',
    Definition: 'gate, door, entrance, opening',
    Frequency: 185,
  },
  {
    Character: '任',
    Pinyin: 'rèn',
    Definition: 'trust to, rely on, appoint; to bear, duty, office; allow',
    Frequency: 186,
  },
  {
    Character: '常',
    Pinyin: 'cháng',
    Definition: 'common, normal, frequent, regular',
    Frequency: 187,
  },
  {
    Character: '先',
    Pinyin: 'xiān',
    Definition: 'first, former, previous',
    Frequency: 188,
  },
  {
    Character: '海',
    Pinyin: 'hǎi',
    Definition: 'sea, ocean; maritime',
    Frequency: 189,
  },
  {
    Character: '通',
    Pinyin: 'tōng',
    Definition: 'pass through, common, communicate',
    Frequency: 190,
  },
  {
    Character: '教',
    Pinyin: 'jiào',
    Definition: 'teach, class',
    Frequency: 191,
  },
  {
    Character: '儿',
    Pinyin: 'ér',
    Definition: 'son, child; KangXi radical 10',
    Frequency: 192,
  },
  {
    Character: '原',
    Pinyin: 'yuán',
    Definition: 'source, origin, beginning',
    Frequency: 193,
  },
  {
    Character: '东',
    Pinyin: 'dōng',
    Definition: 'east, eastern, eastward',
    Frequency: 194,
  },
  {
    Character: '声',
    Pinyin: 'shēng',
    Definition: 'sound, voice, noise; tone; music',
    Frequency: 195,
  },
  {
    Character: '提',
    Pinyin: 'tí',
    Definition: 'hold in hand; lift in hand',
    Frequency: 196,
  },
  {
    Character: '立',
    Pinyin: 'lì',
    Definition: 'stand; let stand; establish, set',
    Frequency: 197,
  },
  {
    Character: '及',
    Pinyin: 'jí',
    Definition: 'extend; reach; come up to; and',
    Frequency: 198,
  },
  {
    Character: '比',
    Pinyin: 'bǐ',
    Definition: 'to compare, liken; comparison; than',
    Frequency: 199,
  },
  {
    Character: '员',
    Pinyin: 'yuán',
    Definition: 'member; personnel, staff member',
    Frequency: 200,
  },
  {
    Character: '解',
    Pinyin: 'jiě',
    Definition: 'loosen, unfasten, untie; explain',
    Frequency: 201,
  },
  {
    Character: '水',
    Pinyin: 'shuǐ',
    Definition: 'water, liquid, lotion, juice',
    Frequency: 202,
  },
  {
    Character: '名',
    Pinyin: 'míng',
    Definition: 'name, rank, title, position',
    Frequency: 203,
  },
  {
    Character: '真',
    Pinyin: 'zhēn',
    Definition: 'real, actual, true, genuine',
    Frequency: 204,
  },
  {
    Character: '论',
    Pinyin: 'lùn',
    Definition: 'debate; discuss; discourse',
    Frequency: 205,
  },
  {
    Character: '处',
    Pinyin: 'chù',
    Definition: 'place, locale; department',
    Frequency: 206,
  },
  {
    Character: '走',
    Pinyin: 'zǒu',
    Definition: 'walk, go on foot; run; leave',
    Frequency: 207,
  },
  {
    Character: '义',
    Pinyin: 'yì',
    Definition: 'right conduct, righteousness',
    Frequency: 208,
  },
  {
    Character: '各',
    Pinyin: 'gè',
    Definition: 'each, individually, every, all',
    Frequency: 209,
  },
  {
    Character: '入',
    Pinyin: 'rù',
    Definition: 'enter, come in(to), join',
    Frequency: 210,
  },
  { Character: '几', Pinyin: 'jǐ', Definition: 'small table', Frequency: 211 },
  {
    Character: '口',
    Pinyin: 'kǒu',
    Definition: 'mouth; open end; entrance, gate',
    Frequency: 212,
  },
  {
    Character: '认',
    Pinyin: 'rèn',
    Definition: 'recognize, know, understand',
    Frequency: 213,
  },
  {
    Character: '条',
    Pinyin: 'tiáo',
    Definition: 'clause, condition; string, stripe',
    Frequency: 214,
  },
  {
    Character: '平',
    Pinyin: 'píng',
    Definition: 'flat, level, even; peaceful',
    Frequency: 215,
  },
  {
    Character: '系',
    Pinyin: 'xì',
    Definition: 'system; line, link, connection',
    Frequency: 216,
  },
  {
    Character: '气',
    Pinyin: 'qì',
    Definition: 'steam, vapor; KangXi radical 84',
    Frequency: 217,
  },
  {
    Character: '题',
    Pinyin: 'tí',
    Definition: 'forehead; title, headline; theme',
    Frequency: 218,
  },
  {
    Character: '活',
    Pinyin: 'huó',
    Definition: 'live, exist, survive; lively',
    Frequency: 219,
  },
  {
    Character: '尔',
    Pinyin: 'ěr',
    Definition: 'you; that, those; final particle',
    Frequency: 220,
  },
  {
    Character: '更',
    Pinyin: 'gèng',
    Definition: 'more, still further, much more',
    Frequency: 221,
  },
  {
    Character: '别',
    Pinyin: 'bié',
    Definition: 'separate, other; do not',
    Frequency: 222,
  },
  {
    Character: '打',
    Pinyin: 'dǎ',
    Definition: 'strike, hit, beat; fight; attack',
    Frequency: 223,
  },
  {
    Character: '女',
    Pinyin: 'nǚ',
    Definition: 'woman, girl; feminine; rad. 38',
    Frequency: 224,
  },
  {
    Character: '变',
    Pinyin: 'biàn',
    Definition: 'change, transform, alter; rebel',
    Frequency: 225,
  },
  { Character: '四', Pinyin: 'sì', Definition: 'four', Frequency: 226 },
  {
    Character: '神',
    Pinyin: 'shén',
    Definition: 'spirit, god, supernatural being',
    Frequency: 227,
  },
  {
    Character: '总',
    Pinyin: 'zǒng',
    Definition: 'collect; overall, altogether',
    Frequency: 228,
  },
  {
    Character: '何',
    Pinyin: 'hé',
    Definition: 'what, why, where, which, how',
    Frequency: 229,
  },
  {
    Character: '电',
    Pinyin: 'diàn',
    Definition: 'electricity; electric; lightning',
    Frequency: 230,
  },
  {
    Character: '数',
    Pinyin: 'shù',
    Definition: 'number; several, count; fate',
    Frequency: 231,
  },
  {
    Character: '安',
    Pinyin: 'ān',
    Definition: 'peaceful, tranquil, quiet',
    Frequency: 232,
  },
  {
    Character: '少',
    Pinyin: 'shǎo',
    Definition: 'few, less, inadequate',
    Frequency: 233,
  },
  {
    Character: '报',
    Pinyin: 'bào',
    Definition: 'report, tell, announce',
    Frequency: 234,
  },
  {
    Character: '才',
    Pinyin: 'cái',
    Definition: 'talent, ability; just, only',
    Frequency: 235,
  },
  {
    Character: '结',
    Pinyin: 'jié',
    Definition: 'knot, tie; join, connect',
    Frequency: 236,
  },
  {
    Character: '反',
    Pinyin: 'fǎn',
    Definition: 'reverse, opposite, contrary, anti',
    Frequency: 237,
  },
  {
    Character: '受',
    Pinyin: 'shòu',
    Definition: 'receive, accept, get; bear, stand',
    Frequency: 238,
  },
  {
    Character: '目',
    Pinyin: 'mù',
    Definition: 'eye; look, see; division, topic',
    Frequency: 239,
  },
  {
    Character: '太',
    Pinyin: 'tài',
    Definition: 'very, too, much; big; extreme',
    Frequency: 240,
  },
  {
    Character: '量',
    Pinyin: 'liàng',
    Definition: 'measure, quantity, capacity',
    Frequency: 241,
  },
  {
    Character: '再',
    Pinyin: 'zài',
    Definition: 'again, twice, re-',
    Frequency: 242,
  },
  {
    Character: '感',
    Pinyin: 'gǎn',
    Definition: 'feel, perceive, emotion',
    Frequency: 243,
  },
  {
    Character: '建',
    Pinyin: 'jiàn',
    Definition: 'build, establish, erect, found',
    Frequency: 244,
  },
  {
    Character: '务',
    Pinyin: 'wù',
    Definition: 'affairs, business; must, should',
    Frequency: 245,
  },
  {
    Character: '做',
    Pinyin: 'zuò',
    Definition: 'work, make; act',
    Frequency: 246,
  },
  {
    Character: '接',
    Pinyin: 'jiē',
    Definition: 'receive; continue; catch; connect',
    Frequency: 247,
  },
  {
    Character: '必',
    Pinyin: 'bì',
    Definition: 'surely, most certainly; must',
    Frequency: 248,
  },
  {
    Character: '场',
    Pinyin: 'chǎng',
    Definition: 'open space, field, market',
    Frequency: 249,
  },
  {
    Character: '件',
    Pinyin: 'jiàn',
    Definition: 'numerary adjunct for article; matter',
    Frequency: 250,
  },
  {
    Character: '计',
    Pinyin: 'jì',
    Definition: 'plan, plot; strategem; scheme',
    Frequency: 251,
  },
  {
    Character: '管',
    Pinyin: 'guǎn',
    Definition: 'pipe, tube, duct; woodwind music',
    Frequency: 252,
  },
  {
    Character: '期',
    Pinyin: 'qī',
    Definition: 'period of time; date; time limit',
    Frequency: 253,
  },
  {
    Character: '市',
    Pinyin: 'shì',
    Definition: 'market, fair; city, town; trade',
    Frequency: 254,
  },
  {
    Character: '直',
    Pinyin: 'zhí',
    Definition: 'straight, erect, vertical',
    Frequency: 255,
  },
  {
    Character: '德',
    Pinyin: 'dé',
    Definition: 'ethics, morality, virtue',
    Frequency: 256,
  },
  {
    Character: '资',
    Pinyin: 'zī',
    Definition: 'property; wealth; capital',
    Frequency: 257,
  },
  {
    Character: '命',
    Pinyin: 'mìng',
    Definition: 'life; destiny, fate, luck; an order, instruction',
    Frequency: 258,
  },
  {
    Character: '山',
    Pinyin: 'shān',
    Definition: 'mountain, hill, peak',
    Frequency: 259,
  },
  {
    Character: '金',
    Pinyin: 'jīn',
    Definition: 'gold; metals in general; money',
    Frequency: 260,
  },
  {
    Character: '指',
    Pinyin: 'zhǐ',
    Definition: 'finger, toe; point, indicate',
    Frequency: 261,
  },
  {
    Character: '克',
    Pinyin: 'kè',
    Definition: 'gram; overcome; transliteration',
    Frequency: 262,
  },
  {
    Character: '许',
    Pinyin: 'xǔ',
    Definition: 'allow, permit; promise; betroth',
    Frequency: 263,
  },
  {
    Character: '统',
    Pinyin: 'tǒng',
    Definition: 'govern, command, control; unite',
    Frequency: 264,
  },
  {
    Character: '区',
    Pinyin: 'qū',
    Definition: 'area, district, region, ward',
    Frequency: 265,
  },
  {
    Character: '保',
    Pinyin: 'bǎo',
    Definition: 'protect, safeguard, defend, care',
    Frequency: 266,
  },
  {
    Character: '至',
    Pinyin: 'zhì',
    Definition: 'reach, arrive; extremely, very',
    Frequency: 267,
  },
  {
    Character: '队',
    Pinyin: 'duì',
    Definition: 'team, group; army unit',
    Frequency: 268,
  },
  {
    Character: '形',
    Pinyin: 'xíng',
    Definition: 'form, shape, appearance',
    Frequency: 269,
  },
  {
    Character: '社',
    Pinyin: 'shè',
    Definition:
      'god of the soil and altars to him; group of families; company, society',
    Frequency: 270,
  },
  {
    Character: '便',
    Pinyin: 'biàn',
    Definition: 'convenience, ease; expedient',
    Frequency: 271,
  },
  {
    Character: '空',
    Pinyin: 'kōng',
    Definition: 'empty, hollow, bare, deserted',
    Frequency: 272,
  },
  {
    Character: '决',
    Pinyin: 'jué',
    Definition: 'decide, determine, judge',
    Frequency: 273,
  },
  {
    Character: '治',
    Pinyin: 'zhì',
    Definition: 'govern, regulate, administer',
    Frequency: 274,
  },
  {
    Character: '展',
    Pinyin: 'zhǎn',
    Definition: 'open, unfold; stretch, extend',
    Frequency: 275,
  },
  {
    Character: '马',
    Pinyin: 'mǎ',
    Definition: 'horse; surname; KangXi radical 187',
    Frequency: 276,
  },
  {
    Character: '科',
    Pinyin: 'kē',
    Definition: 'section, department, science',
    Frequency: 277,
  },
  {
    Character: '司',
    Pinyin: 'sī',
    Definition: 'take charge of, control, manage; officer',
    Frequency: 278,
  },
  {
    Character: '五',
    Pinyin: 'wǔ',
    Definition: 'five; surname',
    Frequency: 279,
  },
  {
    Character: '基',
    Pinyin: 'jī',
    Definition: 'foundation, base',
    Frequency: 280,
  },
  {
    Character: '眼',
    Pinyin: 'yǎn',
    Definition: 'eye; eyelet, hole, opening',
    Frequency: 281,
  },
  {
    Character: '书',
    Pinyin: 'shū',
    Definition: 'book, letter, document; writings',
    Frequency: 282,
  },
  {
    Character: '非',
    Pinyin: 'fēi',
    Definition: 'not, negative, non-; oppose',
    Frequency: 283,
  },
  {
    Character: '则',
    Pinyin: 'zé',
    Definition: 'rule, law, regulation; grades',
    Frequency: 284,
  },
  {
    Character: '听',
    Pinyin: 'tīng',
    Definition: 'hear; understand; obey, comply',
    Frequency: 285,
  },
  {
    Character: '白',
    Pinyin: 'bái',
    Definition: 'white; pure, unblemished; bright',
    Frequency: 286,
  },
  {
    Character: '却',
    Pinyin: 'què',
    Definition: 'still, but; decline; retreat',
    Frequency: 287,
  },
  {
    Character: '界',
    Pinyin: 'jiè',
    Definition: 'boundary, limit; domain; society; the world',
    Frequency: 288,
  },
  {
    Character: '达',
    Pinyin: 'dá',
    Definition: 'arrive at, reach; intelligent; smooth, slippery',
    Frequency: 289,
  },
  {
    Character: '光',
    Pinyin: 'guāng',
    Definition: 'light, brilliant, shine; only',
    Frequency: 290,
  },
  {
    Character: '放',
    Pinyin: 'fàng',
    Definition: 'put, release, free, liberate',
    Frequency: 291,
  },
  {
    Character: '强',
    Pinyin: 'qiáng',
    Definition: 'strong, powerful, energetic',
    Frequency: 292,
  },
  {
    Character: '即',
    Pinyin: 'jí',
    Definition: 'promptly, quickly, immediately',
    Frequency: 293,
  },
  {
    Character: '像',
    Pinyin: 'xiàng',
    Definition: 'a picture, image, figure; to resemble',
    Frequency: 294,
  },
  {
    Character: '难',
    Pinyin: 'nán',
    Definition: 'difficult, arduous, hard; unable',
    Frequency: 295,
  },
  {
    Character: '且',
    Pinyin: 'qiě',
    Definition: 'moreover, also (post-subject); about to, will soon (pre-verb)',
    Frequency: 296,
  },
  {
    Character: '权',
    Pinyin: 'quán',
    Definition: 'power, right, authority',
    Frequency: 297,
  },
  {
    Character: '思',
    Pinyin: 'sī',
    Definition: 'think, consider, ponder; final particle',
    Frequency: 298,
  },
  {
    Character: '王',
    Pinyin: 'wáng',
    Definition: 'king, ruler; royal; surname',
    Frequency: 299,
  },
  {
    Character: '象',
    Pinyin: 'xiàng',
    Definition: 'elephant; ivory; figure, image',
    Frequency: 300,
  },
  {
    Character: '完',
    Pinyin: 'wán',
    Definition: 'complete, finish, settle; whole',
    Frequency: 301,
  },
  {
    Character: '设',
    Pinyin: 'shè',
    Definition: 'build; establish; display',
    Frequency: 302,
  },
  {
    Character: '式',
    Pinyin: 'shì',
    Definition: 'style, system, formula, rule',
    Frequency: 303,
  },
  {
    Character: '色',
    Pinyin: 'sè',
    Definition:
      'color, tint, hue, shade; form, body; beauty, desire for beauty',
    Frequency: 304,
  },
  {
    Character: '路',
    Pinyin: 'lù',
    Definition: 'road, path, street; journey',
    Frequency: 305,
  },
  {
    Character: '记',
    Pinyin: 'jì',
    Definition: 'record; keep in mind, remember',
    Frequency: 306,
  },
  {
    Character: '南',
    Pinyin: 'nán',
    Definition: 'south; southern part; southward',
    Frequency: 307,
  },
  {
    Character: '品',
    Pinyin: 'pǐn',
    Definition: 'article, product, commodity',
    Frequency: 308,
  },
  {
    Character: '住',
    Pinyin: 'zhù',
    Definition: 'reside, live at, dwell, lodge; stop',
    Frequency: 309,
  },
  {
    Character: '告',
    Pinyin: 'gào',
    Definition: 'tell, announce, inform; accuse',
    Frequency: 310,
  },
  {
    Character: '类',
    Pinyin: 'lèi',
    Definition: 'class, group, kind, category',
    Frequency: 311,
  },
  {
    Character: '求',
    Pinyin: 'qiú',
    Definition: 'seek; demand, request; beseech',
    Frequency: 312,
  },
  {
    Character: '据',
    Pinyin: 'jù',
    Definition: 'to occupy, take possession of; a base, position',
    Frequency: 313,
  },
  {
    Character: '程',
    Pinyin: 'chéng',
    Definition: 'journey, trip; schedule, agenda',
    Frequency: 314,
  },
  {
    Character: '北',
    Pinyin: 'běi',
    Definition: 'north; northern; northward',
    Frequency: 315,
  },
  {
    Character: '边',
    Pinyin: 'biān',
    Definition: 'edge, margin, side, border',
    Frequency: 316,
  },
  {
    Character: '死',
    Pinyin: 'sǐ',
    Definition: 'die; dead; death',
    Frequency: 317,
  },
  {
    Character: '张',
    Pinyin: 'zhāng',
    Definition: 'stretch, extend, expand; sheet',
    Frequency: 318,
  },
  {
    Character: '该',
    Pinyin: 'gāi',
    Definition: 'should, ought to, need to',
    Frequency: 319,
  },
  {
    Character: '交',
    Pinyin: 'jiāo',
    Definition: 'mix; intersect; exchange, communicate; deliver',
    Frequency: 320,
  },
  {
    Character: '规',
    Pinyin: 'guī',
    Definition: 'rules, regulations, customs, law',
    Frequency: 321,
  },
  {
    Character: '万',
    Pinyin: 'wàn',
    Definition: 'ten thousand; innumerable',
    Frequency: 322,
  },
  {
    Character: '取',
    Pinyin: 'qǔ',
    Definition: 'take, receive, obtain; select',
    Frequency: 323,
  },
  {
    Character: '拉',
    Pinyin: 'lā',
    Definition: 'pull, drag; seize, hold; lengthen',
    Frequency: 324,
  },
  {
    Character: '格',
    Pinyin: 'gé',
    Definition: 'pattern, standard, form; style',
    Frequency: 325,
  },
  {
    Character: '望',
    Pinyin: 'wàng',
    Definition: 'to look at, look forward; to hope, expect',
    Frequency: 326,
  },
  {
    Character: '觉',
    Pinyin: 'jué',
    Definition: 'to wake up from sleep; conscious',
    Frequency: 327,
  },
  {
    Character: '术',
    Pinyin: 'shù',
    Definition: 'art, skill, special feat; method, technique',
    Frequency: 328,
  },
  {
    Character: '领',
    Pinyin: 'lǐng',
    Definition: 'neck; collar; lead, guide',
    Frequency: 329,
  },
  {
    Character: '共',
    Pinyin: 'gòng',
    Definition: 'together with, all, total; to share',
    Frequency: 330,
  },
  {
    Character: '确',
    Pinyin: 'què',
    Definition: 'sure, certain; real, true',
    Frequency: 331,
  },
  {
    Character: '传',
    Pinyin: 'chuán',
    Definition: 'summon; propagate, transmit',
    Frequency: 332,
  },
  {
    Character: '师',
    Pinyin: 'shī',
    Definition: 'teacher, master, specialist',
    Frequency: 333,
  },
  {
    Character: '观',
    Pinyin: 'guān',
    Definition: 'see, observe, view; appearance',
    Frequency: 334,
  },
  {
    Character: '清',
    Pinyin: 'qīng',
    Definition: 'clear, pure, clean; peaceful',
    Frequency: 335,
  },
  {
    Character: '今',
    Pinyin: 'jīn',
    Definition: 'now, today, modern era',
    Frequency: 336,
  },
  {
    Character: '切',
    Pinyin: 'qiè',
    Definition: 'cut, mince, slice, carve',
    Frequency: 337,
  },
  {
    Character: '院',
    Pinyin: 'yuàn',
    Definition: 'courtyard, yard, court; school',
    Frequency: 338,
  },
  {
    Character: '让',
    Pinyin: 'ràng',
    Definition: 'allow, permit, yield, concede',
    Frequency: 339,
  },
  {
    Character: '识',
    Pinyin: 'shí',
    Definition: 'recognize, understand, know',
    Frequency: 340,
  },
  {
    Character: '候',
    Pinyin: 'hòu',
    Definition: 'wait; expect; visit; greet',
    Frequency: 341,
  },
  {
    Character: '带',
    Pinyin: 'dài',
    Definition: 'belt, girdle, band, strap, zone',
    Frequency: 342,
  },
  {
    Character: '导',
    Pinyin: 'dǎo',
    Definition: 'direct, guide, lead, conduct',
    Frequency: 343,
  },
  {
    Character: '争',
    Pinyin: 'zhēng',
    Definition: 'dispute, fight, contend, strive',
    Frequency: 344,
  },
  {
    Character: '运',
    Pinyin: 'yùn',
    Definition: 'run; simplified form of 運 luck, fortune; ship, transport',
    Frequency: 345,
  },
  {
    Character: '笑',
    Pinyin: 'xiào',
    Definition: 'smile, laugh, giggle; snicker',
    Frequency: 346,
  },
  {
    Character: '飞',
    Pinyin: 'fēi',
    Definition: 'fly; go quickly; dart; high',
    Frequency: 347,
  },
  {
    Character: '风',
    Pinyin: 'fēng',
    Definition: 'wind; air; manners, atmosphere',
    Frequency: 348,
  },
  {
    Character: '步',
    Pinyin: 'bù',
    Definition: 'step, pace; walk, stroll',
    Frequency: 349,
  },
  {
    Character: '改',
    Pinyin: 'gǎi',
    Definition: 'change, alter; improve, remodel',
    Frequency: 350,
  },
  {
    Character: '收',
    Pinyin: 'shōu',
    Definition: 'gather together, collect; harvest',
    Frequency: 351,
  },
  {
    Character: '根',
    Pinyin: 'gēn',
    Definition: 'root, base(d on); foundation',
    Frequency: 352,
  },
  {
    Character: '干',
    Pinyin: 'gàn',
    Definition: 'oppose, offend; invade; dried',
    Frequency: 353,
  },
  {
    Character: '造',
    Pinyin: 'zào',
    Definition: 'construct, build, make, begin; prepare',
    Frequency: 354,
  },
  {
    Character: '言',
    Pinyin: 'yán',
    Definition: 'words, speech; speak, say',
    Frequency: 355,
  },
  {
    Character: '联',
    Pinyin: 'lián',
    Definition: 'connect, join; associate, ally',
    Frequency: 356,
  },
  {
    Character: '持',
    Pinyin: 'chí',
    Definition: 'sustain, support; hold, grasp',
    Frequency: 357,
  },
  {
    Character: '组',
    Pinyin: 'zǔ',
    Definition: 'class; section, department',
    Frequency: 358,
  },
  { Character: '每', Pinyin: 'měi', Definition: 'every, each', Frequency: 359 },
  {
    Character: '济',
    Pinyin: 'jì',
    Definition: 'help, aid, relieve; ferry, cross',
    Frequency: 360,
  },
  {
    Character: '车',
    Pinyin: 'chē',
    Definition: 'cart, vehicle; carry in cart',
    Frequency: 361,
  },
  {
    Character: '亲',
    Pinyin: 'qīn',
    Definition:
      'relatives, parents; intimate the hazel nut or filbert tree a thorny tree',
    Frequency: 362,
  },
  {
    Character: '极',
    Pinyin: 'jí',
    Definition: 'extreme, utmost, furthest, final',
    Frequency: 363,
  },
  {
    Character: '林',
    Pinyin: 'lín',
    Definition: 'forest, grove; surname',
    Frequency: 364,
  },
  {
    Character: '服',
    Pinyin: 'fú',
    Definition: 'clothes; wear, dress',
    Frequency: 365,
  },
  {
    Character: '快',
    Pinyin: 'kuài',
    Definition: 'rapid, quick, speedy, fast; soon',
    Frequency: 366,
  },
  {
    Character: '办',
    Pinyin: 'bàn',
    Definition: 'manage, do, handle; deal with',
    Frequency: 367,
  },
  {
    Character: '议',
    Pinyin: 'yì',
    Definition: 'consult, talk over, discuss',
    Frequency: 368,
  },
  {
    Character: '往',
    Pinyin: 'wǎng',
    Definition: 'go, depart; past, formerly',
    Frequency: 369,
  },
  {
    Character: '元',
    Pinyin: 'yuán',
    Definition: 'first; dollar; origin; head',
    Frequency: 370,
  },
  {
    Character: '英',
    Pinyin: 'yīng',
    Definition: 'petal, flower, leaf; brave, a hero; England, English',
    Frequency: 371,
  },
  {
    Character: '士',
    Pinyin: 'shì',
    Definition: 'scholar, gentleman; soldier',
    Frequency: 372,
  },
  {
    Character: '证',
    Pinyin: 'zhèng',
    Definition: 'prove, confirm, verify; proof',
    Frequency: 373,
  },
  {
    Character: '近',
    Pinyin: 'jìn',
    Definition: 'near, close; approach; intimate',
    Frequency: 374,
  },
  {
    Character: '失',
    Pinyin: 'shī',
    Definition: 'lose; make mistake, neglect',
    Frequency: 375,
  },
  {
    Character: '转',
    Pinyin: 'zhuǎn',
    Definition: 'shift, move, turn',
    Frequency: 376,
  },
  {
    Character: '夫',
    Pinyin: 'fū',
    Definition: 'man, male adult, husband; those',
    Frequency: 377,
  },
  { Character: '令', Pinyin: 'lìng', Definition: '', Frequency: 378 },
  {
    Character: '准',
    Pinyin: 'zhǔn',
    Definition: 'approve, allow, permit; in accord',
    Frequency: 379,
  },
  {
    Character: '布',
    Pinyin: 'bù',
    Definition: 'cotton cloth, textiles, linen',
    Frequency: 380,
  },
  {
    Character: '始',
    Pinyin: 'shǐ',
    Definition: 'begin, start; then, only then',
    Frequency: 381,
  },
  {
    Character: '怎',
    Pinyin: 'zěn',
    Definition: 'what? why? how?',
    Frequency: 382,
  },
  {
    Character: '呢',
    Pinyin: 'ne',
    Definition: 'interrogative or emphatic final; (Cant.) this',
    Frequency: 383,
  },
  {
    Character: '存',
    Pinyin: 'cún',
    Definition: 'exist, live, be; survive; remain',
    Frequency: 384,
  },
  {
    Character: '未',
    Pinyin: 'wèi',
    Definition: 'not yet; 8th terrestrial branch',
    Frequency: 385,
  },
  {
    Character: '远',
    Pinyin: 'yuǎn',
    Definition: 'distant, remote, far; profound',
    Frequency: 386,
  },
  {
    Character: '叫',
    Pinyin: 'jiào',
    Definition: 'cry, shout; hail, greet, call',
    Frequency: 387,
  },
  {
    Character: '台',
    Pinyin: 'tái',
    Definition: 'platform; unit; term of address',
    Frequency: 388,
  },
  {
    Character: '单',
    Pinyin: 'dān',
    Definition: 'single, individual, only; lone',
    Frequency: 389,
  },
  {
    Character: '影',
    Pinyin: 'yǐng',
    Definition: 'shadow; image, reflection; photograph',
    Frequency: 390,
  },
  {
    Character: '具',
    Pinyin: 'jù',
    Definition: 'tool, implement; draw up, write',
    Frequency: 391,
  },
  {
    Character: '罗',
    Pinyin: 'luō',
    Definition: 'net for catching birds; gauze',
    Frequency: 392,
  },
  {
    Character: '字',
    Pinyin: 'zì',
    Definition: 'letter, character, word',
    Frequency: 393,
  },
  {
    Character: '爱',
    Pinyin: 'ài',
    Definition: 'love, be fond of, like',
    Frequency: 394,
  },
  {
    Character: '击',
    Pinyin: 'jī',
    Definition: 'strike, hit, beat; attack, fight',
    Frequency: 395,
  },
  {
    Character: '流',
    Pinyin: 'liú',
    Definition: 'flow, circulate, drift; class',
    Frequency: 396,
  },
  {
    Character: '备',
    Pinyin: 'bèi',
    Definition: 'prepare, ready, perfect',
    Frequency: 397,
  },
  {
    Character: '兵',
    Pinyin: 'bīng',
    Definition: 'soldier, troops',
    Frequency: 398,
  },
  {
    Character: '连',
    Pinyin: 'lián',
    Definition: 'join, connect; continuous; even',
    Frequency: 399,
  },
  {
    Character: '调',
    Pinyin: 'diào',
    Definition: 'transfer, move, change; tune',
    Frequency: 400,
  },
  {
    Character: '深',
    Pinyin: 'shēn',
    Definition: 'deep; depth; far; very, extreme',
    Frequency: 401,
  },
  {
    Character: '商',
    Pinyin: 'shāng',
    Definition: 'commerce, business, trade',
    Frequency: 402,
  },
  {
    Character: '算',
    Pinyin: 'suàn',
    Definition: 'count, calculate, figure; plan',
    Frequency: 403,
  },
  {
    Character: '质',
    Pinyin: 'zhì',
    Definition: 'matter, material, substance',
    Frequency: 404,
  },
  {
    Character: '团',
    Pinyin: 'tuán',
    Definition: 'sphere, ball, circle; mass, lump',
    Frequency: 405,
  },
  {
    Character: '集',
    Pinyin: 'jí',
    Definition: 'assemble, collect together',
    Frequency: 406,
  },
  {
    Character: '百',
    Pinyin: 'bǎi',
    Definition: 'one hundred; numerous, many',
    Frequency: 407,
  },
  {
    Character: '需',
    Pinyin: 'xū',
    Definition: 'need, require, must',
    Frequency: 408,
  },
  {
    Character: '价',
    Pinyin: 'jià',
    Definition: 'price, value',
    Frequency: 409,
  },
  {
    Character: '花',
    Pinyin: 'huā',
    Definition: 'flower; blossoms',
    Frequency: 410,
  },
  {
    Character: '党',
    Pinyin: 'dǎng',
    Definition: 'political party, gang, faction',
    Frequency: 411,
  },
  {
    Character: '华',
    Pinyin: 'huá',
    Definition: 'flowery; illustrious; Chinese',
    Frequency: 412,
  },
  {
    Character: '城',
    Pinyin: 'chéng',
    Definition: 'castle; city, town; municipality',
    Frequency: 413,
  },
  {
    Character: '石',
    Pinyin: 'shí',
    Definition: 'stone, rock, mineral; rad. 112',
    Frequency: 414,
  },
  {
    Character: '级',
    Pinyin: 'jí',
    Definition: 'level, rank, class; grade',
    Frequency: 415,
  },
  {
    Character: '整',
    Pinyin: 'zhěng',
    Definition: 'orderly, neat, tidy; whole',
    Frequency: 416,
  },
  {
    Character: '府',
    Pinyin: 'fǔ',
    Definition: 'prefecture; prefect; government',
    Frequency: 417,
  },
  {
    Character: '离',
    Pinyin: 'lí',
    Definition: 'rare beast; strange; elegant',
    Frequency: 418,
  },
  {
    Character: '况',
    Pinyin: 'kuàng',
    Definition: 'condition, situation; furthermore',
    Frequency: 419,
  },
  { Character: '亚', Pinyin: 'yà', Definition: 'Asia; second', Frequency: 420 },
  {
    Character: '请',
    Pinyin: 'qǐng',
    Definition: 'ask, request; invite; please',
    Frequency: 421,
  },
  {
    Character: '技',
    Pinyin: 'jì',
    Definition: 'skill, ability, talent, ingenuity',
    Frequency: 422,
  },
  {
    Character: '际',
    Pinyin: 'jì',
    Definition: 'border, boundary, juncture',
    Frequency: 423,
  },
  {
    Character: '约',
    Pinyin: 'yuē',
    Definition: 'treaty, agreement, covenant',
    Frequency: 424,
  },
  {
    Character: '示',
    Pinyin: 'shì',
    Definition: 'show, manifest; demonstrate',
    Frequency: 425,
  },
  {
    Character: '复',
    Pinyin: 'fù',
    Definition: 'return; repeat; repeatedly',
    Frequency: 426,
  },
  {
    Character: '病',
    Pinyin: 'bìng',
    Definition: 'illness, sickness, disease',
    Frequency: 427,
  },
  {
    Character: '息',
    Pinyin: 'xī',
    Definition: 'rest, put stop to, end, cease',
    Frequency: 428,
  },
  {
    Character: '究',
    Pinyin: 'jiū',
    Definition: 'examine, investigate',
    Frequency: 429,
  },
  {
    Character: '线',
    Pinyin: 'xiàn',
    Definition: 'line, thread, wire; clue',
    Frequency: 430,
  },
  {
    Character: '似',
    Pinyin: 'shì',
    Definition: 'resemble, similar to; as if, seem',
    Frequency: 431,
  },
  {
    Character: '官',
    Pinyin: 'guān',
    Definition: 'official, public servant',
    Frequency: 432,
  },
  {
    Character: '火',
    Pinyin: 'huǒ',
    Definition: 'fire, flame; burn; anger, rage',
    Frequency: 433,
  },
  {
    Character: '断',
    Pinyin: 'duàn',
    Definition: 'sever, cut off; interrupt',
    Frequency: 434,
  },
  {
    Character: '精',
    Pinyin: 'jīng',
    Definition: 'essence; semen; spirit',
    Frequency: 435,
  },
  {
    Character: '满',
    Pinyin: 'mǎn',
    Definition: 'fill; full, satisfied',
    Frequency: 436,
  },
  {
    Character: '支',
    Pinyin: 'zhī',
    Definition: 'disperse, pay; support; branch',
    Frequency: 437,
  },
  {
    Character: '视',
    Pinyin: 'shì',
    Definition: 'look at, inspect, observe, see',
    Frequency: 438,
  },
  {
    Character: '消',
    Pinyin: 'xiāo',
    Definition: 'vanish, die out; melt away',
    Frequency: 439,
  },
  {
    Character: '越',
    Pinyin: 'yuè',
    Definition: 'exceed, go beyond; the more ...',
    Frequency: 440,
  },
  {
    Character: '器',
    Pinyin: 'qì',
    Definition: 'receptacle, vessel; instrument',
    Frequency: 441,
  },
  {
    Character: '容',
    Pinyin: 'róng',
    Definition: 'looks, appearance; figure, form',
    Frequency: 442,
  },
  {
    Character: '照',
    Pinyin: 'zhào',
    Definition: 'shine, illumine, reflect',
    Frequency: 443,
  },
  {
    Character: '须',
    Pinyin: 'xū',
    Definition: 'must, have to, necessary',
    Frequency: 444,
  },
  { Character: '九', Pinyin: 'jiǔ', Definition: 'nine', Frequency: 445 },
  {
    Character: '增',
    Pinyin: 'zēng',
    Definition: 'increase, add to, augment',
    Frequency: 446,
  },
  {
    Character: '研',
    Pinyin: 'yán',
    Definition: 'grind, rub; study, research',
    Frequency: 447,
  },
  {
    Character: '写',
    Pinyin: 'xiě',
    Definition: 'write; draw, sketch; compose',
    Frequency: 448,
  },
  {
    Character: '称',
    Pinyin: 'chēng',
    Definition: 'call; name, brand; address; say',
    Frequency: 449,
  },
  {
    Character: '企',
    Pinyin: 'qǐ',
    Definition: 'plan a project; stand on tiptoe',
    Frequency: 450,
  },
  {
    Character: '八',
    Pinyin: 'bā',
    Definition: 'eight; all around, all sides',
    Frequency: 451,
  },
  {
    Character: '功',
    Pinyin: 'gōng',
    Definition: 'achievement, merit, good result',
    Frequency: 452,
  },
  {
    Character: '吗',
    Pinyin: 'ma',
    Definition: 'final interrogative particle',
    Frequency: 453,
  },
  {
    Character: '包',
    Pinyin: 'bāo',
    Definition: 'wrap, pack, bundle; package',
    Frequency: 454,
  },
  {
    Character: '片',
    Pinyin: 'piàn',
    Definition: 'slice, splinter, strip; rad. 91',
    Frequency: 455,
  },
  {
    Character: '史',
    Pinyin: 'shǐ',
    Definition: 'history, chronicle, annals',
    Frequency: 456,
  },
  {
    Character: '委',
    Pinyin: 'wěi',
    Definition: 'appoint, send, commission',
    Frequency: 457,
  },
  {
    Character: '乎',
    Pinyin: 'hū',
    Definition: 'interrogative or exclamatory final particle',
    Frequency: 458,
  },
  {
    Character: '查',
    Pinyin: 'chá',
    Definition: 'investigate, examine, seek into',
    Frequency: 459,
  },
  {
    Character: '轻',
    Pinyin: 'qīng',
    Definition: 'light; easy, simple; gentle',
    Frequency: 460,
  },
  { Character: '易', Pinyin: 'yì', Definition: 'change; easy', Frequency: 461 },
  {
    Character: '早',
    Pinyin: 'zǎo',
    Definition: 'early; soon; morning',
    Frequency: 462,
  },
  {
    Character: '曾',
    Pinyin: 'céng',
    Definition: 'already; sign of past',
    Frequency: 463,
  },
  {
    Character: '除',
    Pinyin: 'chú',
    Definition: 'eliminate, remove, except',
    Frequency: 464,
  },
  {
    Character: '农',
    Pinyin: 'nóng',
    Definition: 'agriculture, farming; farmer',
    Frequency: 465,
  },
  {
    Character: '找',
    Pinyin: 'zhǎo',
    Definition: 'search, seek, look for; find',
    Frequency: 466,
  },
  {
    Character: '装',
    Pinyin: 'zhuāng',
    Definition: 'dress, clothes, attire; fill',
    Frequency: 467,
  },
  {
    Character: '广',
    Pinyin: 'guǎng',
    Definition: 'wide, extensive, broad; rad. 53',
    Frequency: 468,
  },
  {
    Character: '显',
    Pinyin: 'xiǎn',
    Definition: 'manifest, display; evident, clear',
    Frequency: 469,
  },
  {
    Character: '吧',
    Pinyin: 'ba',
    Definition: 'emphatic final particle',
    Frequency: 470,
  },
  { Character: '阿', Pinyin: 'ā', Definition: '', Frequency: 471 },
  {
    Character: '李',
    Pinyin: 'lǐ',
    Definition: 'plum; judge; surname',
    Frequency: 472,
  },
  {
    Character: '标',
    Pinyin: 'biāo',
    Definition: 'mark, symbol, label, sign; stand the bole of a tree',
    Frequency: 473,
  },
  {
    Character: '谈',
    Pinyin: 'tán',
    Definition: 'talk; conversation; surname',
    Frequency: 474,
  },
  {
    Character: '吃',
    Pinyin: 'chī',
    Definition: 'eat; drink; suffer, endure, bear',
    Frequency: 475,
  },
  {
    Character: '图',
    Pinyin: 'tú',
    Definition: 'diagram; chart, map, picture',
    Frequency: 476,
  },
  {
    Character: '念',
    Pinyin: 'niàn',
    Definition: 'think of, recall, study',
    Frequency: 477,
  },
  { Character: '六', Pinyin: 'liù', Definition: 'number six', Frequency: 478 },
  {
    Character: '引',
    Pinyin: 'yǐn',
    Definition: 'to pull, draw out, attract; to stretch',
    Frequency: 479,
  },
  {
    Character: '历',
    Pinyin: 'lì',
    Definition: 'history; calendar',
    Frequency: 480,
  },
  {
    Character: '首',
    Pinyin: 'shǒu',
    Definition: 'head; first; leader, chief; a poem',
    Frequency: 481,
  },
  {
    Character: '医',
    Pinyin: 'yī',
    Definition: 'cure, heal; doctor, medical',
    Frequency: 482,
  },
  {
    Character: '局',
    Pinyin: 'jú',
    Definition: 'bureau, office; circumstance',
    Frequency: 483,
  },
  {
    Character: '突',
    Pinyin: 'tū',
    Definition: 'suddenly, abruptly, unexpectedly',
    Frequency: 484,
  },
  {
    Character: '专',
    Pinyin: 'zhuān',
    Definition: 'monopolize, take sole possession',
    Frequency: 485,
  },
  {
    Character: '费',
    Pinyin: 'fèi',
    Definition: 'expenses, expenditures, fee',
    Frequency: 486,
  },
  {
    Character: '号',
    Pinyin: 'hào',
    Definition: 'mark, sign; symbol; number',
    Frequency: 487,
  },
  {
    Character: '尽',
    Pinyin: 'jǐn',
    Definition: 'exhaust, use up; deplete',
    Frequency: 488,
  },
  {
    Character: '另',
    Pinyin: 'lìng',
    Definition: 'another, separate, other',
    Frequency: 489,
  },
  {
    Character: '周',
    Pinyin: 'zhōu',
    Definition: 'Zhou dynasty; circumference',
    Frequency: 490,
  },
  {
    Character: '较',
    Pinyin: 'jiào',
    Definition: 'compare; comparatively, more',
    Frequency: 491,
  },
  {
    Character: '注',
    Pinyin: 'zhù',
    Definition: 'concentrate, focus, direct',
    Frequency: 492,
  },
  {
    Character: '语',
    Pinyin: 'yǔ',
    Definition: 'language, words; saying, expression',
    Frequency: 493,
  },
  {
    Character: '仅',
    Pinyin: 'jǐn',
    Definition: 'only, merely, solely, just',
    Frequency: 494,
  },
  {
    Character: '考',
    Pinyin: 'kǎo',
    Definition: 'examine, test; investigate',
    Frequency: 495,
  },
  {
    Character: '落',
    Pinyin: 'luò',
    Definition: 'fall, drop; net income, surplus',
    Frequency: 496,
  },
  {
    Character: '青',
    Pinyin: 'qīng',
    Definition: 'blue, green, black; young',
    Frequency: 497,
  },
  {
    Character: '随',
    Pinyin: 'suí',
    Definition: 'follow, listen to, submit to',
    Frequency: 498,
  },
  {
    Character: '选',
    Pinyin: 'xuǎn',
    Definition: 'choose, select; elect; election',
    Frequency: 499,
  },
  {
    Character: '列',
    Pinyin: 'liè',
    Definition: 'a line; to arrange in order, classify',
    Frequency: 500,
  },
  {
    Character: '武',
    Pinyin: 'wǔ',
    Definition: 'military; martial, warlike',
    Frequency: 501,
  },
  {
    Character: '红',
    Pinyin: 'hóng',
    Definition: 'red, vermillion; blush, flush',
    Frequency: 502,
  },
  {
    Character: '响',
    Pinyin: 'xiǎng',
    Definition: 'make sound, make noise; sound',
    Frequency: 503,
  },
  {
    Character: '虽',
    Pinyin: 'suī',
    Definition: 'although, even if',
    Frequency: 504,
  },
  {
    Character: '推',
    Pinyin: 'tuī',
    Definition: 'push, expel; push forward',
    Frequency: 505,
  },
  {
    Character: '势',
    Pinyin: 'shì',
    Definition: 'power, force; tendency',
    Frequency: 506,
  },
  {
    Character: '参',
    Pinyin: 'cān',
    Definition: 'take part in, intervene; ginseng',
    Frequency: 507,
  },
  {
    Character: '希',
    Pinyin: 'xī',
    Definition: 'rare; hope, expect, strive for',
    Frequency: 508,
  },
  {
    Character: '古',
    Pinyin: 'gǔ',
    Definition: 'old, classic, ancient',
    Frequency: 509,
  },
  {
    Character: '众',
    Pinyin: 'zhòng',
    Definition: 'multitude, crowd; masses, public',
    Frequency: 510,
  },
  {
    Character: '构',
    Pinyin: 'gòu',
    Definition: 'frame, building, structure',
    Frequency: 511,
  },
  {
    Character: '房',
    Pinyin: 'fáng',
    Definition: 'house, building; room',
    Frequency: 512,
  },
  { Character: '半', Pinyin: 'bàn', Definition: 'half', Frequency: 513 },
  {
    Character: '节',
    Pinyin: 'jié',
    Definition: 'knot, node, joint; section',
    Frequency: 514,
  },
  {
    Character: '土',
    Pinyin: 'tǔ',
    Definition: 'soil, earth; items made of earth',
    Frequency: 515,
  },
  {
    Character: '投',
    Pinyin: 'tóu',
    Definition: 'throw, cast, fling, pitch; jump',
    Frequency: 516,
  },
  {
    Character: '某',
    Pinyin: 'mǒu',
    Definition: 'certain thing or person',
    Frequency: 517,
  },
  {
    Character: '案',
    Pinyin: 'àn',
    Definition: 'table, bench; legal case',
    Frequency: 518,
  },
  {
    Character: '黑',
    Pinyin: 'hēi',
    Definition: 'black; dark; evil, sinister',
    Frequency: 519,
  },
  {
    Character: '维',
    Pinyin: 'wéi',
    Definition: 'maintain, preserve, safeguard',
    Frequency: 520,
  },
  {
    Character: '革',
    Pinyin: 'gé',
    Definition: 'leather, animal hides; rad. 177',
    Frequency: 521,
  },
  {
    Character: '划',
    Pinyin: 'huà',
    Definition: 'to row or paddle boat; to scratch',
    Frequency: 522,
  },
  {
    Character: '敌',
    Pinyin: 'dí',
    Definition: 'enemy, foe, rival; resist',
    Frequency: 523,
  },
  {
    Character: '致',
    Pinyin: 'zhì',
    Definition: 'send, deliver, present; cause',
    Frequency: 524,
  },
  {
    Character: '陈',
    Pinyin: 'chén',
    Definition: 'exhibit, display; plead; a surname',
    Frequency: 525,
  },
  {
    Character: '律',
    Pinyin: 'lǜ',
    Definition: 'statute, principle, regulation',
    Frequency: 526,
  },
  {
    Character: '足',
    Pinyin: 'zú',
    Definition: 'foot; attain, satisfy, enough',
    Frequency: 527,
  },
  {
    Character: '态',
    Pinyin: 'tài',
    Definition: 'manner, bearing, attitude',
    Frequency: 528,
  },
  {
    Character: '护',
    Pinyin: 'hù',
    Definition: 'protect, guard, defend, shelter',
    Frequency: 529,
  },
  { Character: '七', Pinyin: 'qī', Definition: 'seven', Frequency: 530 },
  {
    Character: '兴',
    Pinyin: 'xìng',
    Definition: 'thrive, prosper, flourish',
    Frequency: 531,
  },
  {
    Character: '派',
    Pinyin: 'pài',
    Definition: 'school of thought, sect, branch',
    Frequency: 532,
  },
  {
    Character: '孩',
    Pinyin: 'hái',
    Definition: 'baby, child; children',
    Frequency: 533,
  },
  {
    Character: '验',
    Pinyin: 'yàn',
    Definition: 'test, examine, inspect; verify',
    Frequency: 534,
  },
  { Character: '责', Pinyin: 'zé', Definition: '', Frequency: 535 },
  {
    Character: '营',
    Pinyin: 'yíng',
    Definition: 'encampment, barracks; manage',
    Frequency: 536,
  },
  {
    Character: '星',
    Pinyin: 'xīng',
    Definition: 'a star, planet; any point of light',
    Frequency: 537,
  },
  {
    Character: '够',
    Pinyin: 'gòu',
    Definition: 'enough, adequate',
    Frequency: 538,
  },
  {
    Character: '章',
    Pinyin: 'zhāng',
    Definition: 'composition; chapter, section',
    Frequency: 539,
  },
  {
    Character: '音',
    Pinyin: 'yīn',
    Definition: 'sound, tone, pitch, pronunciation',
    Frequency: 540,
  },
  {
    Character: '跟',
    Pinyin: 'gēn',
    Definition: 'heel; to follow, accompany; with',
    Frequency: 541,
  },
  {
    Character: '志',
    Pinyin: 'zhì',
    Definition: 'purpose, will, determination; annals',
    Frequency: 542,
  },
  {
    Character: '底',
    Pinyin: 'dǐ',
    Definition: 'bottom, underneath, underside',
    Frequency: 543,
  },
  {
    Character: '站',
    Pinyin: 'zhàn',
    Definition: 'stand up; a stand, station',
    Frequency: 544,
  },
  {
    Character: '严',
    Pinyin: 'yán',
    Definition: 'strict, rigorous, rigid; stern',
    Frequency: 545,
  },
  {
    Character: '巴',
    Pinyin: 'bā',
    Definition: 'greatly desire, anxiously hope',
    Frequency: 546,
  },
  {
    Character: '例',
    Pinyin: 'lì',
    Definition: 'precedent, example; regulation',
    Frequency: 547,
  },
  {
    Character: '防',
    Pinyin: 'fáng',
    Definition: 'defend; prevent; embankment',
    Frequency: 548,
  },
  {
    Character: '族',
    Pinyin: 'zú',
    Definition: 'a family clan, ethnic group, tribe',
    Frequency: 549,
  },
  {
    Character: '供',
    Pinyin: 'gōng',
    Definition: 'supply, provide for; offer in worship',
    Frequency: 550,
  },
  {
    Character: '效',
    Pinyin: 'xiào',
    Definition: 'result, effect; effectiveness',
    Frequency: 551,
  },
  {
    Character: '续',
    Pinyin: 'xù',
    Definition: 'continue, carry on; succeed',
    Frequency: 552,
  },
  {
    Character: '施',
    Pinyin: 'shī',
    Definition: 'grant, bestow; give; act; name',
    Frequency: 553,
  },
  {
    Character: '留',
    Pinyin: 'liú',
    Definition: 'stop, halt; stay, detain, keep',
    Frequency: 554,
  },
  {
    Character: '讲',
    Pinyin: 'jiǎng',
    Definition: 'explain; discuss; talk',
    Frequency: 555,
  },
  {
    Character: '型',
    Pinyin: 'xíng',
    Definition: 'pattern, model, type; law; mold',
    Frequency: 556,
  },
  {
    Character: '料',
    Pinyin: 'liào',
    Definition: 'consider, conjecture; materials, ingredients',
    Frequency: 557,
  },
  {
    Character: '终',
    Pinyin: 'zhōng',
    Definition: 'end; finally, in the end',
    Frequency: 558,
  },
  {
    Character: '答',
    Pinyin: 'dá',
    Definition: 'answer, reply; return; assent to',
    Frequency: 559,
  },
  {
    Character: '紧',
    Pinyin: 'jǐn',
    Definition: 'tense, tight, taut; firm, secure',
    Frequency: 560,
  },
  {
    Character: '黄',
    Pinyin: 'huáng',
    Definition: 'yellow; surname',
    Frequency: 561,
  },
  {
    Character: '绝',
    Pinyin: 'jué',
    Definition: 'to cut, sever, break off, terminate',
    Frequency: 562,
  },
  {
    Character: '奇',
    Pinyin: 'qí',
    Definition: 'strange, unusual, uncanny, occult',
    Frequency: 563,
  },
  {
    Character: '察',
    Pinyin: 'chá',
    Definition: 'examine, investigate; notice',
    Frequency: 564,
  },
  {
    Character: '母',
    Pinyin: 'mǔ',
    Definition: 'mother; female elders; female',
    Frequency: 565,
  },
  {
    Character: '京',
    Pinyin: 'jīng',
    Definition: 'capital city',
    Frequency: 566,
  },
  {
    Character: '段',
    Pinyin: 'duàn',
    Definition: 'section, piece, division',
    Frequency: 567,
  },
  {
    Character: '依',
    Pinyin: 'yī',
    Definition: 'rely on, be set in; consent, obey a wish',
    Frequency: 568,
  },
  {
    Character: '批',
    Pinyin: 'pī',
    Definition: 'comment, criticize; wholesale',
    Frequency: 569,
  },
  {
    Character: '群',
    Pinyin: 'qún',
    Definition: '(same as 羣) group, crowd, multitude, mob',
    Frequency: 570,
  },
  {
    Character: '项',
    Pinyin: 'xiàng',
    Definition: 'neck, nape of neck; sum; funds',
    Frequency: 571,
  },
  {
    Character: '故',
    Pinyin: 'gù',
    Definition: 'ancient, old; reason, because',
    Frequency: 572,
  },
  {
    Character: '按',
    Pinyin: 'àn',
    Definition: 'put hand on, press down with hand',
    Frequency: 573,
  },
  {
    Character: '河',
    Pinyin: 'hé',
    Definition: 'river; stream; yellow river',
    Frequency: 574,
  },
  {
    Character: '米',
    Pinyin: 'mǐ',
    Definition: 'hulled or husked uncooked rice',
    Frequency: 575,
  },
  {
    Character: '围',
    Pinyin: 'wéi',
    Definition: 'surround, encircle, corral',
    Frequency: 576,
  },
  {
    Character: '江',
    Pinyin: 'jiāng',
    Definition: 'large river; yangzi; surname',
    Frequency: 577,
  },
  {
    Character: '织',
    Pinyin: 'zhī',
    Definition: 'weave, knit; organize, unite',
    Frequency: 578,
  },
  {
    Character: '害',
    Pinyin: 'hài',
    Definition: 'injure, harm; destroy, kill',
    Frequency: 579,
  },
  {
    Character: '斗',
    Pinyin: 'dòu',
    Definition: 'Chinese peck; liquid measure',
    Frequency: 580,
  },
  {
    Character: '双',
    Pinyin: 'shuāng',
    Definition: 'set of two, pair, couple; both',
    Frequency: 581,
  },
  {
    Character: '境',
    Pinyin: 'jìng',
    Definition: 'boundary, frontier; area, region',
    Frequency: 582,
  },
  {
    Character: '客',
    Pinyin: 'kè',
    Definition: 'guest, traveller; customer',
    Frequency: 583,
  },
  {
    Character: '纪',
    Pinyin: 'jì',
    Definition: 'record, annal, historical account',
    Frequency: 584,
  },
  {
    Character: '采',
    Pinyin: 'cǎi',
    Definition: 'collect, gather; pick, pluck',
    Frequency: 585,
  },
  {
    Character: '举',
    Pinyin: 'jǔ',
    Definition: 'raise, lift up; recommend',
    Frequency: 586,
  },
  {
    Character: '杀',
    Pinyin: 'shā',
    Definition: 'kill, slaughter, murder; hurt',
    Frequency: 587,
  },
  {
    Character: '攻',
    Pinyin: 'gōng',
    Definition: 'attack, assault; criticize',
    Frequency: 588,
  },
  {
    Character: '父',
    Pinyin: 'fù',
    Definition: 'father; KangXi radical 88',
    Frequency: 589,
  },
  { Character: '苏', Pinyin: 'sū', Definition: '', Frequency: 590 },
  {
    Character: '密',
    Pinyin: 'mì',
    Definition: 'dense, thick, close; intimate',
    Frequency: 591,
  },
  {
    Character: '低',
    Pinyin: 'dī',
    Definition: 'low; to lower, hang, bend, bow',
    Frequency: 592,
  },
  {
    Character: '朝',
    Pinyin: 'cháo',
    Definition: 'dynasty; morning',
    Frequency: 593,
  },
  {
    Character: '友',
    Pinyin: 'yǒu',
    Definition: 'friend, companion; fraternity',
    Frequency: 594,
  },
  {
    Character: '诉',
    Pinyin: 'sù',
    Definition: 'accuse; sue; inform; narrate',
    Frequency: 595,
  },
  {
    Character: '止',
    Pinyin: 'zhǐ',
    Definition: 'stop, halt, desist; detain',
    Frequency: 596,
  },
  {
    Character: '细',
    Pinyin: 'xì',
    Definition: 'fine, tiny; slender, thin',
    Frequency: 597,
  },
  {
    Character: '愿',
    Pinyin: 'yuàn',
    Definition: 'sincere, honest, virtuous',
    Frequency: 598,
  },
  {
    Character: '千',
    Pinyin: 'qiān',
    Definition: 'thousand; many, numerous; very; (Cant.) a cheater, swindler',
    Frequency: 599,
  },
  { Character: '值', Pinyin: 'zhí', Definition: 'price', Frequency: 600 },
];
